project:
  type: website
  output-dir: docs

website:
  title: "Quarto with RStudio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/https://github.com/usman-afzali/quarto-and-rstudio
      - icon: twitter
        href: https://twitter.com/UsmanAfzali
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

